/**
* Domain models can generally be either very lean or more robust.
*/

//Lean Domain
package demo
class Person{
    String firstName
    String lastName
    int age
}

static constraints = {
    age range: 0..120
}

//Domain Test
@TestFor(Person)
class PersonSpec extends Specification{
    // Specifies the names of the individual tests that are generated by the where block.
    // Also causes the individual tests to be 'unrolled' rather than just 1 test method.
    @Unroll('validate on a person with age #personAge should have returned #shouldBeValid')
    void 'test age verification'(){
        expect:
        new Person(age: personAge).validate(['age']) == shouldBeValid

        where:
        personAge   | shouldBeValid
        -2          | false
        -1          | false
        0           | true
        1           | true
        119         | true
        120         | true
        121         | false
        122         | false
    }
}